# A declaration of an instance that this hApp needs to have installed.
# `name` here is just an internal name to reference the given DNA inside the rest of this bundle.

bridges = []

[[instances]]
name = "Passthrough"
id = "instance"
dna_hash = "QmZ1z6SKKeG53RQWwma7k644GUaX2dj4v5HEEGTs8ScRyJ"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.6/passthrough-dna.dna.json"


[[UIs]]
name = "Passthrough Test hApp"
uri = "https://github.com/holochain/passthrough-dna/releases/download/v0.0.6/ui.zip"

[[UIs.instance_references]]
ui_handle = "test-instance"
instance_id = "instance"


