
bridges = []

[[instances]]
name = "H_Wiki"
id = "__H_Wiki"
dna_hash = "QmTJwkhiFKUeK7QsRCjk1t6XCBAm31bkmHfsAEa6ZuvxCa"
uri = "https://github.com/eyss/h-wiki-back/releases/download/0.2/h-wiki-back.dna.json"

[[UIs]]
name = "H-Wiki"
uri = "https://github.com/eyss/h-wiki-back/releases/download/0.2/front.zip"

[[UIs.instance_references]]
ui_handle = "__H_Wiki"
instance_id = "__H_Wiki"
