bridges = []

[[instances]]
name = "Basic Chat Public"
id = "__basic-chat-public"
dna_hash = "QmXWUEQwuoG7TqNBMy6GZT9eP83BsY25juLm1zqzmGgHVw"
uri = "https://github.com/holochain/basic-chat/releases/download/v0.1.2/basic-chat.dna.json"

[[UIs]]
name = "Basic Chat"
id = "basic-chat-ui"
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/holochain/basic-chat/releases/download/v0.1.2/ui.zip"

[[UIs.instance_references]]
ui_handle = "basic-chat"
instance_id = "__basic-chat-public"
