bridges = []

[[instances]]
name = "HoloFuel"
id = "__holofuel"
dna_hash = "QmdRUPDZ3xoZDJj2ciCX3Wk6eRPe9z6pnZpiVHK9cu6R6K"
uri = "https://holo-host.github.io/holofuel/releases/download/v0.13.0-alpha1/holofuel.dna.json"

[[UIs]]
name = "HoloFuel UI"
id = "holofuel-ui"
ui_bundle_hash = "Qm34abcde"
uri = "https://github.com/Holo-Host/hp-admin/releases/download/0.1.2-alpha1/holofuel-ui.zip"

[[UIs.instance_references]]
ui_handle = "holofuel"
instance_id = "__holofuel"
